name: CI
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          # - '1.10'
          # - '1.11'
          # - '1.12'
          - '1.13'
        os:
          # - ubuntu-latest
          - macOS-latest
          # - windows-latest
        arch:
          - x64
          - aarch64
        exclude:
          - os: macOS-latest
            arch: x64
          - os: ubuntu-latest
            arch: aarch64
          - os: windows-latest
            arch: aarch64
    steps:
      - uses: actions/checkout@v1
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      # Add Python dependencies only on non-Windows
      - name: Add CondaPkg and PythonCall
        if: runner.os != 'Windows'
        run: julia --project=test -e 'using Pkg; Pkg.add("CondaPkg"); Pkg.add("PythonCall"); using CondaPkg; CondaPkg.add("python"; version=">=3.10,<3.14")'
      - uses: julia-actions/julia-buildpkg@latest

      - uses: julia-actions/julia-runtest@latest
